#!/bin/bash

function display_help() {
    echo "Usage: catdir [OPTIONS]"
    echo
    echo "Utility to display contents of files in the current directory based on specific patterns."
    echo
    echo "Options:"
    echo "  -d, --directory <directory>    Specify the directory to operate on. If not provided, use the current directory."
    echo "  -e, --exclude <pattern>        Exclude files matching the pattern."
    echo "  -i, --include <pattern>        Include only files that match the pattern. Multiple patterns can be specified."
    echo "  -g, --git                      Include .git/*"
    echo "  -h, --help                     Display this help message and exit."
    echo "      --logo                     Output a cat emoji and a folder emoji."
    echo
    echo "Examples:"
    echo "  catdir --directory '/home/user/documents'       Operate on /home/user/documents directory."
    echo "  catdir --include '*.txt' --include '*.md'       Only include .txt and .md files."
    echo "  catdir --exclude './.git/*' --include '*.txt'   Exclude .git directory and only include .txt files."
    echo "  catdir --git                                    Include .git/*"
    echo
}

exclusions="! -path '**/.git/**'"
inclusions=""
include_only=false
directory="."

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -d|--directory)
            shift
            directory="$1"
            shift
            ;;
        -e|--exclude)
            shift
            exclusions="${exclusions} ! -path '$1'"
            shift
            ;;
        -i|--include)
            include_only=true
            shift
            [ -z "${inclusions}" ] && inclusions="-path '$1'" || inclusions="${inclusions} -o -path '$1'"
            shift
            ;;
        -g|--git)
            exclusions=""
            shift
            ;;
        -h|--help)
            display_help
            exit 0
            ;;
        --logo)
            echo "🐱📁"
            exit 0
            ;;
        *)
            # Handle unexpected input
            echo "Unexpected argument: $1"
            echo "Use -h for help."
            exit 1
            ;;
    esac
done

if $include_only && [ -z "${inclusions}" ]; then
    echo "You specified -i without any pattern."
    exit 1
fi

find_cmd="find ${directory} -type f"

[ -n "${exclusions}" ] && find_cmd="${find_cmd} ${exclusions}"
$include_only && find_cmd="${find_cmd} \( ${inclusions} \)"

echo "Constructed find command: $find_cmd"  # Let's print out the constructed command

eval "${find_cmd}" | while IFS= read -r file; do
    echo "=====${file}====="
    cat "$file"
    echo
done
